{% set name = "zfit_interface" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zfit_interface-{{ version }}.tar.gz
  sha256: af7e8ed409f136187b2cd4def723504f9d619738668e963af388a79121239f74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - setuptools_scm_git_archive
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - typing-extensions
    - uhi

test:
  imports:
    - zfit_interface
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zfit/zfit-interface
  summary: zfit model fitting interface for HEP
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonas-eschle
